---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dahua-companion
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: dahua-companion-secret
    template:
      engineVersion: v2
      data:
        # EMQX
        MQTT_USERNAME: "{{ .DAHUA_COMPANION_USERNAME }}"
        MQTT_PASSWORD: "{{ .DAHUA_COMPANION_PASSWORD }}"
        # DOORBELL
        HOSTNAME_OR_IP: "{{ .DOORBELL_HOST }}"
        USERNAME: "{{ .DOORBELL_USERNAME }}"
        PASSWORD: "{{ .DOORBELL_PASSWORD }}"
  dataFrom:
    - extract:
        key: EMQX
    - extract:
        key: doorbell
