---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dahua-companion
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: dahua-companion-secret
    template:
      engineVersion: v2
      data:
        # EMQX
        MQTT_USERNAME: "{{ .DAHUA_EMQX_USERNAME }}"
        MQTT_PASSWORD: "{{ .DAHUA_EMQX_PASSWORD }}"
        # DOORBELL
        HOSTNAME_OR_IP: "{{ .DOORBELL_HOST }}"
        DAHUA_USERNAME: "{{ .DOORBELL_USERNAME }}"
        DAHUA_PASSWORD: "{{ .DOORBELL_PASSWORD }}"
  data:
    - secretKey: DAHUA_EMQX_USERNAME
      remoteRef:
        key: DAHUA_EMQX_USERNAME
    - secretKey: DAHUA_EMQX_PASSWORD
      remoteRef:
        key: DAHUA_EMQX_PASSWORD
    - secretKey: DOORBELL_HOST
      remoteRef:
        key: DOORBELL_HOST
    - secretKey: DOORBELL_USERNAME
      remoteRef:
        key: DOORBELL_USERNAME
    - secretKey: DOORBELL_PASSWORD
      remoteRef:
        key: DOORBELL_PASSWORD
