---
# Push OBC credentials to Bitwarden as separate secrets
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cloudnative-pg-push
  namespace: rook-ceph
spec:
  updatePolicy: Replace
  refreshInterval: 1m
  secretStoreRefs:
    - name: bitwarden-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: cloudnative-pg
  data:
    - match:
        secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          remoteKey: CNPG_BUCKET_ACCESS_KEY
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: CNPG_BUCKET_SECRET_KEY
