---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-adguard-webhook
  labels:
    app.kubernetes.io/name: external-dns-adguard-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns-adguard-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns-adguard-webhook
      annotations:
        secret.reloader.stakater.com/reload: external-dns-adguard-secret
    spec:
      containers:
        - name: webhook
          image: ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.0
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8081
              name: http-health
              protocol: TCP
          env:
            - name: ADGUARD_URL
              value: "https://adguard.${SECRET_DOMAIN}"
            - name: ADGUARD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: external-dns-adguard-secret
                  key: username
            - name: ADGUARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: external-dns-adguard-secret
                  key: password
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_READ_TIMEOUT
              value: "60s"
            - name: SERVER_WRITE_TIMEOUT
              value: "60s"
          livenessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: http-health
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000