---
apiVersion: v1
kind: Service
metadata:
  name: external-dns-adguard-webhook
  labels:
    app.kubernetes.io/name: external-dns-adguard-webhook
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: external-dns-adguard-webhook
  type: ClusterIP