---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/pkg/apis/upgrade.cattle.io/v1/plan.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos-controlplane
  namespace: system-upgrade
spec:
  # Wait for worker Plan to complete before starting
  version: v1.13.0
  serviceAccountName: system-upgrade
  concurrency: 1
  exclusive: true
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
  upgrade:
    image: ghcr.io/siderolabs/installer:v1.13.8@sha256:1c6a41e8324d85742ba97968c427a10122a47273244c209e5dd2d4b207516e7d
  drain:
    force: false
    disableEviction: false
    deleteLocalData: true
    ignoreDaemonSets: true
    skipWaitForDeleteTimeout: 180
    timeout: 900
    gracePeriod: 1200
