---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rbac.yaml
  - ./cronjob.yaml
configMapGenerator:
  - name: node-fencer-script
    files:
      - fence.sh=./resources/fence.sh
generatorOptions:
  disableNameSuffixHash: true
