apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: actions-runner-controller-auth-secret
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: actions-runner-controller-auth-secret
  map:
    - bwSecretId: d5af4483-779d-41e5-a53a-b1940041052a
      secretKeyName: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - bwSecretId: aeed0e85-1dbe-447b-a5d1-b19400421c83
      secretKeyName: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    - bwSecretId: 042bbf1d-a544-4e40-8fd8-b194004259e3
      secretKeyName: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
