apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./ingress.yaml
  - ./podmonitor.yaml
configMapGenerator:
  - name: emqx-loki-rules
    files:
      - emqx.yaml=./resources/lokirule.yaml
    options:
      labels:
        loki_rule: "true"
generatorOptions:
  disableNameSuffixHash: true
