apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 10
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 473
        runAsGroup: 473
        fsGroup: 473
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
    controllers:
      minio:
        labels:
          nfsMount: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2024-06-11T03-13-30Z
            env:
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.${SECRET_DOMAIN},https://s3.${SECRET_DOMAIN}
              MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_DOMAIN}
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_PROMETHEUS_URL: https://prometheus.${SECRET_DOMAIN}
              MINIO_PROMETHEUS_AUTH_TYPE: public
              MINIO_SERVER_URL: https://s3.${SECRET_DOMAIN}
              MINIO_UPDATE: "off"
              TZ: ${TIME_ZONE}
            envFrom:
              - secretRef:
                  name: &secret minio-secret
            args: ["server", "/data", "--console-address", ":9001"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: &api-port 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 4Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9001
          s3:
            port: *api-port
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: s3
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "Host $host";
            more_set_headers "X-Forwarded-For $remote_addr"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      api:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "Host $host";
            more_set_headers "X-Forwarded-For $remote_addr"
        hosts:
          - host: &s3Host s3.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: s3
        tls:
          - hosts:
              - *s3Host
    persistence:
      data:
        type: nfs
        globalMounts:
          - path: /data
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: NFS_SERVER
      targetPath: persistence.data.server
    - kind: Secret
      name: *secret
      valuesKey: MINIO_NFS_PATH
      targetPath: persistence.data.path
