apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: minio-secret
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: minio-secret
  map:
    - bwSecretId: 3f925c27-f5b1-4447-926e-b18c018b44b5
      secretKeyName: MINIO_ROOT_USER
    - bwSecretId: dcaf166f-6601-4282-b96e-b18c018b5f9d
      secretKeyName: MINIO_ROOT_PASSWORD
    - bwSecretId: b5ef35c4-6037-4b53-9530-b18c018abf50
      secretKeyName: NFS_SERVER
    - bwSecretId: c94a0374-6dfd-469d-b8dd-b18c018adf2d
      secretKeyName: MINIO_NFS_PATH
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
