apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:unlrBiCOzQ22OUYhnA==,iv:a5G0OmMHr3riIdEnvWwOnW3e5U+HGuOAazRGevpo/lo=,tag:G5717se8SX6lBRaQ8Jdq+Q==,type:str]
    password: ENC[AES256_GCM,data:57YhOAPCzXESjjh1RsqWI2XY2kKrkXheqBOWnfMejM/QbYWjHqSJEb6dV8MlBDh1K2Qc6meDlhNqcKUuTdpNTw==,iv:kw/c0/Ag0xSfdzLiC54AXL3MTGarXB0fPmXfYfOMPqY=,tag:SQ7ezitcwLa0Zy8qAJeaqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmFwNjJrNExSTk9rR1RM
            UjhWZ1p0eTRsWVh2RjcwOWFuQUZDN0dTTzJrCmtvYSt5RXp4dTR0T0JpaFV6RHlr
            cnBSZE44bEVHWjU3WCtNbGtKNWEyVzQKLS0tIHhCdXFES3ZPYzNVbFQyWldSRC9q
            SnZVRVBDeWFlcGtOei9hS0dqdWFIdFEKFVdJnp/x6635lkyDwLU7yuYfVMwkwitu
            H6LPNYa9/fOyFESh5QnGCmIQ62R5ncGlio1rMMpCsy7xlXsk6JaALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T15:19:06Z"
    mac: ENC[AES256_GCM,data:CJjng7xKqluW2UNChPi8/maCFu5uuyQq+SkpxEbCcpUBpOYjn8psRAs6p4Q/DSEn8Sir60xTlz1vlm71lazIBWBfnsp6LRJUAlhteOCHVskjXg4eF1u9COOiN0z3xGgFLO4Qjh+XgqQ6lA76tAhjb5a4u4QtKsb3RccCaB+Ujqg=,iv:uDI8P2xsslzTvs3A0Y9z3AWHMrxHAjDSkAGSCwLZUJs=,tag:BrlJiMi3xNj+kep/NvGokA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
