rtsp:
  # https://github.com/blakeblackshear/frigate/issues/10181
  default_query: mp4 # Needed for frigate to work
# webrtc:
#   listen: :8555
#   candidates:
#     - 192.168.42.124:8555
#     - stun:8555
#   ice_servers:
#     - urls:
#        - stun:stun.cloudflare.com:3478
streams:
  doorbell: rtsp://admin:backup90@192.168.5.198/cam/realmonitor?channel=1&subtype=0
  doorbell_sub: rtsp://admin:backup90@192.168.5.198/cam/realmonitor?channel=1&subtype=1
