apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral-tpu
spec:
  rules:
    - name: coral.tpu
      labels:
        coral.feature.node.kubernetes.io/tpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: { op: In, value: ["0880"] }
            vendor: { op: In, value: ["1ac1"] }
