apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpu-device
spec:
  rules:
    - # Intel integrated graphics
      name: intel.gpu
      labels:
        intel.feature.node.kubernetes.io/gpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            # Class
            class: { op: In, value: ["0300", "0380"] }
            # 8086 = Intel
            vendor: { op: In, value: ["8086"] }
