---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflared-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        TUNNEL_ID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        credentials.json: |-
          {"AccountTag":"{{ .CLOUDFLARE_ACCOUNT_TAG }}","TunnelSecret":"{{ .CLOUDFLARE_TUNNEL_SECRET }}","TunnelID":"{{ .CLOUDFLARE_TUNNEL_ID }}"}
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_TAG
      remoteRef:
        key: CLOUDFLARE_ACCOUNT_TAG
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: CLOUDFLARE_TUNNEL_SECRET
    - secretKey: CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: CLOUDFLARE_TUNNEL_ID
