apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2OqjT6wGBF5C2MdZKI/Gp32wTp8Zyn38NQ3avlQpV0gBNKKz,iv:jNy5wy4Rzj6pdmX04Dz+aDaW5UNJT8ug+ibK4XjoogI=,tag:bTMO0MVvkPd+6twCABKbTw==,type:str]
    credentials.json: ENC[AES256_GCM,data:7cTh0KtWBq93PWeBPDCdt62RxwgBOB0rvHBWrmG+jYR9Wtr8Dz210ZZ0xMFb6YpR7klopwBclJXLSPEHDHrNUnZ6JrHGAiQKGcrnvY9fouy9MoX8/nJq/GucZqw5R4DHSKl8kekVYJrOQYZKtSDFwzpPlm2YmvuYC6w4/fn1r8Kh/7y5n07fhp0PvI3Y4oRCUgs5maBX6XkMgt+uFUfXtBhlNDyTyZ/6hzwAgebztA==,iv:fhfy4MAtZnjANgneaQZ0u2pta8B1Zdtt8P4CNWm5H78=,tag:yPNrLArXQ1uzGWWztvu3/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIclo2S0xLTEV6WW5EaFh2
            WHZMS0QwdkxxMTBhTEJVdTJDbmlUOVNUWldvClJMZmNkcXZoOW9tdEhub3EweUNm
            cjl6aUZVZ3pPeG9SbGUwV1E4L2NJU0UKLS0tIHRMbkJIeUo1SVBpb2xHbndCM043
            d3kwRENoYTE1SUNYaGh1dkoyVHQ5RUEKVJJZ9rwwxV2Eo33cK6x9rp0D/0t7eRmM
            kEt20ZXzWwPKfkZTqG+ZP3TNyZrtr6UPejNuPHSKP38tVahggCM3Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T06:44:00Z"
    mac: ENC[AES256_GCM,data:QdOtRGTeqzu/5cv/5fjWaN87cETUoJLl3g4LUqD8KBxoDmop9kvXDDBWpNNwGCMHmSt+yOy02hacv+q24Zjt1mf5S6THTrXEoD6+pEoUnpK8QJFvV3TEoq4UcN7VyMYTO1XJbtNJZ7YOcuLSrI6aNjKXhwyLEOLgHEnkszkXCFA=,iv:Ij4GGVpCtTifx1x9pGyKfpWjWOVuAUyXIb4rrBaN44k=,tag:j5TsyD/rYFvCpaumnGAN5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
