apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:7wFkxbYYTJx48AWlJRpig+1o/pjqAXG8PYB/XqNKbn5YpjK/,iv:akn7rNtT5qexpO8BSJN4POQI3RMGejwMYCeWpztRwaM=,tag:qd0RhWiTRIBygVIUv75DOg==,type:str]
    credentials.json: ENC[AES256_GCM,data:TVg0+tMD23hAIXs5Cir4P17GEEWi5Bq9dvDNKkVfsiAlK+8np1cFsyr4nPBd/R6x+n8y9sFWslLacXluRwXXjVokRFSLo5YumKCUU3eimoLbfkmJyaAG+4vlL028+cwaLHrmr2lvbnk3ISdqF0B1DokDeNApoEqRYWnAudDBRIOPyT2J+9huPlWkTBkOxEzziVs2RvOyYA1/OuNv9y7CXaTztxFiKJi1Gyf3Q1jLRg==,iv:7WHcqBv3rF62fo4rmWqr2OZb+VRGSU2luORRfDypWyQ=,tag:w+UAlrfiUT2KQJVgUxBigw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSTFZbStDZmN2R2NuWCtu
            L0lCeGtnSXB5TmRjbUwvUnViTlllakJERHhBCkRmUFJZMHRXaVRYQzFWNW5CYUpO
            dzZpZXR4SkRJckYyQVEyYzZ3cm5LakEKLS0tIHdObDJMS2hxdFQ4YXdIejI4VnJY
            Q2UwUzFsTDlmWk5aVkorZHIyQmkyd1UKyQhYdiVNxeoUwDGwMPu4i4iq4pOtSDNg
            uyaJz4QpGGugqKgq2zXO4VeFwPvaE7uWZoM0VdgPO0OZF1BX7GdzJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T08:25:49Z"
    mac: ENC[AES256_GCM,data:ROmyA6IIEdPAbT/b/+YceHMfvUJWBlgq8lFuGNNiav2EZV3b4wgyRpNPRIM3QBpfYianC2UJ5hbASsVE2K76hCjpXWmm2ny26h4B5FJg5YV7fyLT6r1MKSl7Sh8lydKDyxLZ2Oq84RvAJR5BTvd4MVIK1SLqC/eI1OHmbyBuyZw=,iv:oBT3cE/aNreTA7x8+K0KYzJO0Jz7ZnXFT9xBYKBWWhY=,tag:ej4AHakMSEMajPpQwxyMWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
