apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:XatD/U0iQn+fd9Guj0QPdsFthVYNM0ygo2s271vrlgSBIVpB,iv:GVshtwB4IYzHNiJo7iZXo2KtiqwbAixi8IctivNHgb4=,tag:8AGOs2EKS7TU+ta97drIcw==,type:str]
    credentials.json: ENC[AES256_GCM,data:8n8+3v+l16ENIwJl0ucyWfnOiDYr+cW/CFwEsEeSMiKX7x+mbJbmhK1kK1WUqPNa7fLVifP2yA1IvmT5pRAqkOTzJ/XHqaJJ4gBxMK2uoYQjKcEuQsVuOwwfYJszyLfazGONo27FB5RlxslKNRdRjSxn+tZp2qV8sK0uyQMVeX496ITh+Ao7fXbSBXqd1AVlccckMYDodPsnEgqbMLVpAMKbox8q6EAamCr5rhnoAg==,iv:5sYBYqH+na1YHF5WPBvOYJreaFgkpMe+Heb19qR2GS0=,tag:DtL7YHRDiM0yCYILjET3IA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTjVNbkJISm9uU3JVRzNT
            UW13Nkhib0xWVkRnY0d2REFGZWZqQ1FZK3hFCms5VkZoY1Rua3E1d3dRbUVKdzU2
            d1pUYmFTRVJJSE04dXpmRkhRL3NJWjgKLS0tIEg4aEJaWiswQnFIakFIbXVHNmVj
            ZVZLWXVDb3FTWlhFVXBlWXpQeTMrTVkKErCCWA1Y54k5jcAqWomA3KvtUpRmHt6l
            1bC9PM58pilcGtYL8RcmcxhHCJTy6rSwf7gSUCdSSAHqIo93P3IC7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T23:30:16Z"
    mac: ENC[AES256_GCM,data:3kbV4ET2TfyWweftVKCiGPUdVoDJVGawZ9c2EHj3QepC62/zySqmzeGgZ25iScIQY5g4gnW/ouF7aKK6Sg/Zx0UDwXDAPms8ZK3lZ1zkmuwGrhGP6uwRF4UTX8D/T74YfzyCnkqzqX7GK7HxC3oBWhN10B1WGyccuELMldx3tmo=,iv:hZrIlLw58vbYBTJKwkWEic2RvAwBnOBLIkRBpbk9BQ4=,tag:v83iw5ZfXd3u6ZYxdj1S9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
