---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: "{{ .Z2M_EXT_PAN_ID }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ .Z2M_PAN_ID }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ .Z2M_NETWORK_KEY }}"
        # EMQX
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ .Z2M_EMQX_USERNAME }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .Z2M_EMQX_PASSWORD }}"
  data:
    - secretKey: Z2M_PAN_ID
      remoteRef:
        key: Z2M_PAN_ID
    - secretKey: Z2M_EXT_PAN_ID
      remoteRef:
        key: Z2M_EXT_PAN_ID
    - secretKey: Z2M_NETWORK_KEY
      remoteRef:
        key: Z2M_NETWORK_KEY
    - secretKey: Z2M_EMQX_USERNAME
      remoteRef:
        key: Z2M_EMQX_USERNAME
    - secretKey: Z2M_EMQX_PASSWORD
      remoteRef:
        key: Z2M_EMQX_PASSWORD
