---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  install:
    remediation:
      retries: 3
  interval: 30m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      zigbee2mqtt:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
              # ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: debug
              ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: true
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 80
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: http://zigbee2mqtt.default.svc.cluster.local
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: true
              ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: true
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://emqx-listeners.database.svc.cluster.local
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ember
              ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://192.168.5.237:6638
              ZIGBEE2MQTT_DATA: /config
            envFrom:
              - secretRef:
                  name: zigbee2mqtt-secret
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.6.1@sha256:22e1fc160163edee0ceef47910211e97e7b0fb18b6bc94c9b799409252409f6a
            # probes:
            #   liveness:
            #     enabled: true
            #   readiness:
            #     enabled: true
            #   startup:
            #     enabled: true
            #     spec:
            #       failureThreshold: 30
            #       periodSeconds: 10
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 10m
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    ingress:
      app:
        annotations:
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Home
          gethomepage.dev/icon: zigbee2mqtt.png
          gethomepage.dev/name: Zigbee
        className: internal
        hosts:
          - host: zigbee.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: zigbee2mqtt
    service:
      app:
        controller: zigbee2mqtt
        type: LoadBalancer
        ports:
          http:
            port: 80
