---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflare-dns-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        api-token: "{{ .CLOUDFLARE_DNS_TOKEN }}"
  data:
    - secretKey: CLOUDFLARE_DNS_TOKEN
      remoteRef:
        key: CLOUDFLARE_DNS_TOKEN
