apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: komf-secret
    template:
      engineVersion: v2
      data:
        KOMF_KAVITA_API_KEY: "{{ .KOMF_KAVITA_API_KEY }}"
  dataFrom:
    - extract:
        key: komf
