apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app komf
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      komf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: sndxr/komf
              tag: latest@sha256:8c2034ad712e2a7097cab6a3783107ac53b72efff56e8995ee2970f7892a747f
            env:
              TZ: ${TIMEZONE}
              KOMF_LOG_LEVEL: INFO
              JAVA_TOOL_OPTIONS: -Xmx512m
            envFrom:
              - secretRef:
                  name: komf-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
    service:
      app:
        controller: komf
        ports:
          http:
            port: 8085
    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
      application-config:
        type: configMap
        name: komf-config
        globalMounts:
          - path: /config/application.yml
            subPath: application.yml
            readOnly: true
  driftDetection:
    mode: enabled
