apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: omegabrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: omegabrr-secret
    template:
      engineVersion: v2
      data:
        AUTOBRR_API_KEY: "{{ .AUTOBRR_API_KEY }}"
        # OMEGABRR_API_KEY: "{{ .OMEGABRR_API_KEY }}"
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: autobrr
    # - extract:
    #     key: omegabrr
    - extract:
        key: radarr
    - extract:
        key: sonarr
