apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omegabrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: omegabrr-secret
    template:
      engineVersion: v2
      data:
        AUTOBRR_API_KEY: "{{ .AUTOBRR_API_KEY }}"
        OMEGABRR_API_KEY: "{{ .OMEGABRR_API_KEY }}"
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
  data:
    - secretKey: AUTOBRR_API_KEY
      remoteRef:
        key: AUTOBRR_API_KEY
    - secretKey: OMEGABRR_API_KEY
      remoteRef:
        key: OMEGABRR_API_KEY
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: SONARR_API_KEY
