apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: thanos-bucket-secret
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: thanos-bucket
  map:
    - bwSecretId: 04214e37-cdfa-487b-80a6-b190015d81d3
      secretKeyName: AWS_ACCESS_KEY_ID
    - bwSecretId: 14ec7675-c9a4-4bc2-830c-b190015d9672
      secretKeyName: AWS_SECRET_ACCESS_KEY
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
