---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../templates/network-policies/default-deny
  - ../../../../templates/network-policies/allow-dns
  - ../../../../templates/network-policies/allow-kube-apiserver
  - ../../../../templates/network-policies/allow-from-monitoring
  - ./egress-acme.yaml
  - ./ingress-webhook.yaml
