---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: litellm-secret
    template:
      engineVersion: v2
      data:
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: litellm
