apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-vpn-secret
stringData:
    #ENC[AES256_GCM,data:Bmi8eiC7+9r/UUeOU55eKd0IK31smtFm2KCoWcGYDp1eYh9FCo6aZoLxaBvFHS4+YsP8pqkU69Fa62Wy9oc539u4YMlloQUmN6w=,iv:VPPUVFReD//EM5FkVTlmbths6GFCBWOuqMgU2fpBJ58=,tag:OsH0epDhonIOc/xJbqjRxw==,type:comment]
    #ENC[AES256_GCM,data:RbSOIbCzUfuJ97imbn1k/Vp/IWd17Isf+lgbS/cLlTrN00FDWURbcwHAMff9PVMVyzZ2rgeGD0JdR5gdMxlah6QnTzqqlVmINFfx,iv:ZKioXKM1bHkWEPlhq24pH9ZNJojHE2D6sKtuhtt3L20=,tag:qw1qUnc0jeBTdUVru8R22g==,type:comment]
    OPENVPN_USER: ENC[AES256_GCM,data:gZdkt4dKqlk=,iv:MO5vWOvI+dLCQqlsEG1xY7qkD+kh/10c3Y+pNvEC/jI=,tag:ru/FJSEGHXbfB8QX+8OCLQ==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:Qpg2skoEVoA=,iv:81CA4rUmQ3UzBarBloUfIl45go3YTS8RqeT01KgV6z0=,tag:gDMqPvkgAXIOWOZBeIPkrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZVhvU2NPVFJZdTlDQldY
            NzRHQ0hkRFBvR0tSZTRnTWVFZ2dZVXdqdGpNCnhFQ1cvOW53NWE3Z1dlUkxNSE1i
            L2tka2dLVStIUm45Tko4YXl4NkdxYW8KLS0tIEkvYVZBRWpkSzhoaGlBSERhdTBE
            WTk0VW8wUlFTSkpDeS9xdlVobFZFUUkKwyUSwA6mZfReCuWmfuECZUNuOWcIfBOZ
            PWKb4z/077C82vtkCC0PuVVmQ4KP2MeKsjJQtDVxioQQdrd/XxT3QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T18:42:27Z"
    mac: ENC[AES256_GCM,data:2kWSRbTNeJiQQJ0keS1c1kXGKomJNQgD2TjaeYaRrPdwg8gyJC6khT2tM7sgEZxDmS/szEYTU6lDu7+zNhuLoG8Cpst4O9JiAHIjaI/JuRgZ0OFmRK77RcOvEcY64hcc1Y3ZUSKtL74NQDQUZ5UeTEpjGU1hzQrZjITHuGm4wJE=,iv:U5ugAMeUnOV3mVNUMlGtpa7vUK3dqRSSebUrAPNZms8=,tag:c2m5V8b7dqK7cCeA4GKocw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
