apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: homepage-secret
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: homepage-secret
  map:
    - bwSecretId: cc22d0b8-abe7-4bb9-b90e-b19001434fb9
      secretKeyName: GF_DATABASE_NAME
    - bwSecretId: b42b6333-53ce-4878-9927-b19001437c46
      secretKeyName: GF_DATABASE_PASSWORD
    - bwSecretId: dd04bedc-e8d3-4c8b-9188-b1900143686c
      secretKeyName: GF_DATABASE_USER
    - bwSecretId: cc22d0b8-abe7-4bb9-b90e-b19001434fb9
      secretKeyName: INIT_POSTGRES_DBNAME
    - bwSecretId: b42b6333-53ce-4878-9927-b19001437c46
      secretKeyName: INIT_POSTGRES_PASS
    - bwSecretId: dd04bedc-e8d3-4c8b-9188-b1900143686c
      secretKeyName: INIT_POSTGRES_USER
    - bwSecretId: 8a5322e7-77b3-4948-9698-b18d01425943
      secretKeyName: INIT_POSTGRES_SUPER_PASS
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
