apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: emqx-secret
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: emqx-secret
  map:
    - bwSecretId: 0fb834f3-99a9-4174-8f75-b18d012dc98a
      secretKeyName: EMQX_DASHBOARD__DEFAULT_USERNAME
    - bwSecretId: aea2c641-d926-4d3a-8398-b18d012ddbcf
      secretKeyName: EMQX_DASHBOARD__DEFAULT_PASSWORD
    - bwSecretId: c274044c-8a95-43d9-9fc5-b18d012df7fd
      secretKeyName: X_EMQX_MQTT_USERNAME
    - bwSecretId: 0afb01f5-65b3-40b4-9dd1-b18d012e152a
      secretKeyName: X_EMQX_MQTT_PASSWORD
    - bwSecretId: 9f357fab-59a1-4985-8003-b18d012e8e01
      secretKeyName: X_EMQX_APIKEY_KEY
    - bwSecretId: d5e598f5-35d3-467e-a1e9-b18d012eb000
      secretKeyName: X_EMQX_APIKEY_SECRET
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
