apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: emqx-secret
    template:
      engineVersion: v2
      data:
        EMQX_DASHBOARD__DEFAULT_USERNAME: "{{ .EMQX_DASHBOARD_USERNAME }}"
        EMQX_DASHBOARD__DEFAULT_PASSWORD: "{{ .EMQX_DASHBOARD_PASSWORD }}"
  dataFrom:
    - extract:
        key: EMQX
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-init-user
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: emqx-init-user-secret
    template:
      engineVersion: v2
      data:
        init-user.json: |
          [
            {
                "user_id": "{{ .EMQX_MQTT_USERNAME }}",
                "password": "{{ .EMQX_MQTT_PASSWORD }}",
                "is_superuser": true
            },
            {
                "user_id": "{{ .HASS_EMQX_USERNAME }}",
                "password": "{{ .HASS_EMQX_PASSWORD }}",
                "is_superuser": false
            },
            {
                "user_id": "{{ .FRIGATE_EMQX_USERNAME }}",
                "password": "{{ .FRIGATE_EMQX_PASSWORD }}",
                "is_superuser": false
            },
            {
                "user_id": "{{ .Z2M_EMQX_USERNAME }}",
                "password": "{{ .Z2M_EMQX_PASSWORD }}",
                "is_superuser": false
            }
          ]
  dataFrom:
    - extract:
        key: EMQX
