apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: emqx-secret
    template:
      engineVersion: v2
      data:
        EMQX_DASHBOARD__DEFAULT_USERNAME: "{{ .EMQX_DASHBOARD_USERNAME }}"
        EMQX_DASHBOARD__DEFAULT_PASSWORD: "{{ .EMQX_DASHBOARD_PASSWORD }}"
  data:
    - secretKey: EMQX_DASHBOARD_USERNAME
      remoteRef:
        key: EMQX_DASHBOARD_USERNAME
    - secretKey: EMQX_DASHBOARD_PASSWORD
      remoteRef:
        key: EMQX_DASHBOARD_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-init-user
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: emqx-init-user-secret
    template:
      engineVersion: v2
      data:
        init-user.json: |
          [
            {
                "user_id": "{{ .EMQX_MQTT_USERNAME }}",
                "password": "{{ .EMQX_MQTT_PASSWORD }}",
                "is_superuser": true
            },
            {
                "user_id": "{{ .HASS_EMQX_USERNAME }}",
                "password": "{{ .HASS_EMQX_PASSWORD }}",
                "is_superuser": false
            },
            {
                "user_id": "{{ .FRIGATE_EMQX_USERNAME }}",
                "password": "{{ .FRIGATE_EMQX_PASSWORD }}",
                "is_superuser": false
            },
            {
                "user_id": "{{ .Z2M_EMQX_USERNAME }}",
                "password": "{{ .Z2M_EMQX_PASSWORD }}",
                "is_superuser": false
            },
            {
                "user_id": "{{ .DAHUA_EMQX_USERNAME }}",
                "password": "{{ .DAHUA_EMQX_PASSWORD }}",
                "is_superuser": false
            },
            {
                "user_id": "roborock",
                "password": "{{ .ROBOROCK_MQTT_PASSWORD }}",
                "is_superuser": false
            },
            {
                "user_id": "ecowitt",
                "password": "{{ .GW1200B_MQTT_PASSWORD }}",
                "is_superuser": false
            }
          ]
  data:
    - secretKey: EMQX_MQTT_USERNAME
      remoteRef:
        key: EMQX_MQTT_USERNAME
    - secretKey: EMQX_MQTT_PASSWORD
      remoteRef:
        key: EMQX_MQTT_PASSWORD
    - secretKey: HASS_EMQX_USERNAME
      remoteRef:
        key: HASS_EMQX_USERNAME
    - secretKey: HASS_EMQX_PASSWORD
      remoteRef:
        key: HASS_EMQX_PASSWORD
    - secretKey: FRIGATE_EMQX_USERNAME
      remoteRef:
        key: FRIGATE_EMQX_USERNAME
    - secretKey: FRIGATE_EMQX_PASSWORD
      remoteRef:
        key: FRIGATE_EMQX_PASSWORD
    - secretKey: Z2M_EMQX_USERNAME
      remoteRef:
        key: Z2M_EMQX_USERNAME
    - secretKey: Z2M_EMQX_PASSWORD
      remoteRef:
        key: Z2M_EMQX_PASSWORD
    - secretKey: DAHUA_EMQX_USERNAME
      remoteRef:
        key: DAHUA_EMQX_USERNAME
    - secretKey: DAHUA_EMQX_PASSWORD
      remoteRef:
        key: DAHUA_EMQX_PASSWORD
    - secretKey: ROBOROCK_MQTT_PASSWORD
      remoteRef:
        key: ROBOROCK_MQTT_PASSWORD
    - secretKey: GW1200B_MQTT_PASSWORD
      remoteRef:
        key: GW1200B_MQTT_PASSWORD
