apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adguard-dns-external
  namespace: network
spec:
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
      - network
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: adguard-dns-external
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
