---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name talos-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .GARAGE_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .GARAGE_SECRET_KEY }}"
  data:
    - secretKey: GARAGE_ACCESS_KEY
      remoteRef:
        key: GARAGE_ACCESS_KEY
    - secretKey: GARAGE_SECRET_KEY
      remoteRef:
        key: GARAGE_SECRET_KEY
