- kubernetes:
    cluster:
      cpu: true
      label: cluster
      memory: true
      show: true
      showLabel: true
    nodes:
      cpu: true
      memory: true
      show: true
      showLabel: true
- openmeteo:
    label: Home
    latitude: {{HOMEPAGE_VAR_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_LONGITUDE}}
    timezone: ${TIMEZONE}
    units: imperial
    cache: 5
