apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:VmWC8yRDRjEtLnMtlID4LCVU0Pp7N7hGLDB+hQP+Mc31A1N5AF4dkQ==,iv:jJ9BVUkYhiWHPhPqdccqkK+uUoA4pF1oGdae/QX/W+w=,tag:VcvGI1kkvO0YzoSeQkzuog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cFcyNUxPckxqeTd2YlM4
            K1djTE84TmY2YUFLZWJIbXA2RHZ5dVExWEFJClRVanZNdWxOMUtsdy9iLzlBdWh1
            dStrVGJKcGQ5YmNjV2ZPZ2Z1SW0yN1UKLS0tIFZwdVR3V2xVZEZhUTdOQUdsTTZZ
            dGQ5NVQ1a0VJQzUrNU1QL1VkZGpxdmcKxftDkVJCIgb9g15NqWBBpu7TgnydURiy
            xOfZcNP3OD5QA3FIKwZJ7r+e2P5MtTEsjfj8M2KYtwlHSMxOD8ECvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T06:44:00Z"
    mac: ENC[AES256_GCM,data:JXiqr08pO0R6lfq0v8n9yCbYhk4JNB7u6lq0vT1PFIyhHd121oPfaUeVKzTsJ3Z8PrPHvCJKYLgENSxjteGCP03ddfAxWrAPAJ2gSWHp39DTURadSMeSKctQxufXEhxiZBS+7t1whAY5Y2TMhwUCpnzUczqJ2Ib7iSABDVR3GNc=,iv:og12UpT2CYlt/0+PEoSQSAjJUlqWjr5h9HCvascsxCg=,tag:gkpf+8KmEM3T7B5U/AYAKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
