apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:J1u53kVN2y7zlC+wYNQzUjfLXDqTASIBLQPpjzzMp5Jx783j1arp5Q==,iv:APnUUOo+M3MT+symyGb2pIi9gKWZd9tf86y2sIqNKpY=,tag:gmbtZTBljy8K5MMU0tLe3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUGd1TXlUVVFjcWx6ZXpk
            dUNYVUVEQlg5eTJHWXdrcVN2NDVVbWN2WnlVClBiMlMveC9CNG1WRmJSbVlaS3Q4
            NWQraG15SGdBTjRRUlNiMUN2WEtidUEKLS0tIHlyeitMWGtmVFlZK2JaVjJLUnFz
            QXFLcXg3d3VsN0xBYTFOL0Y5NmIzVkUKUmsvJHhw4Ir2j7n4MvOkFXB4MyDCARh8
            2VvJqJ/IOzAv7wqrQaU3FOf9ZvalRoVkbm7a6DXw5hqNOVFl7mNdQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T08:25:48Z"
    mac: ENC[AES256_GCM,data:C8DVIY6MfRBRjqd3ZxiSA+DATIrBygjy2Ep37TPMn8+6c/wCo8nAEsHe5dXwIREQIphe/kxUtKYL4TQf1qVC0UHisiw71lxl2eEOmpdMvROSoWlKbb3ohlPiyWiRlk/Oe5O+2hQQVu9iYNres7aDjg96oCHShRkMCIzfwOJVKDI=,iv:Uy6v9U7InAk4G8es8tBWaHGuHlwsfBqD0Y70pEEVbm8=,tag:ZEGC//QjItJ2BNTC2BQrMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
