apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed
  namespace: cert-manager
spec:
  isCA: true
  commonName: self-signed
  subject:
    organizations:
      - ${SECRET_DOMAIN}
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-secret
