---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ambientweather2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      ambientweather2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          ambientweather2mqtt:
            image:
              repository: ghcr.io/neilenns/ambientweather2mqtt
              tag: v4.9.1@sha256:6ef6b9b236a795ad65201cdcca27afbdb055fa4d3956598b6e309203601c8676
            env:
              MQTT_SERVER: http://emqx-listeners.database.svc.cluster.local:1883
              PORT: &port 80
              STATION_MAC_ADDRESS: 80:7d:3a:4f:28:34
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: ambientweather2mqtt-secrets
    resources:
      requests:
        cpu: 5m
        memory: 47M
      limits:
        memory: 47M
    service:
      app:
        controller: ambientweather2mqtt
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${AMBIENTWEATHER_LB}
        ports:
          http:
            port: *port
