apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app readarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      readarr:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.2@sha256:ae89578925b480f5972f237dda2f7a37efe36aff500d3e7bd1d3a6a3181e4191
            envFrom: &envFrom
              - secretRef:
                  name: readarr-secret
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/readarr
              tag: 0.4.10.2739
            env:
              READARR__APP__INSTANCENAME: Readarr
              READARR__APP__THEME: dark
              READARR__AUTH__METHOD: External
              READARR__AUTH__REQUIRED: DisabledForLocalAddresses
              READARR__LOG__DBENABLED: "False"
              READARR__LOG__LEVEL: info
              READARR__SERVER__PORT: &port 80
              READARR__UPDATE__BRANCH: develop
              TZ: ${TIMEZONE}
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
          exportarr:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.3.0
            args:
              - readarr
            env:
              PORT: &metricsPort 9707
              URL: http://localhost:80
              API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: readarr-secret
                    key: READARR__AUTH__APIKEY
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: readarr
        ports:
          http:
            port: *port
          metrics:
            port: *metricsPort
    ingress:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Readarr
          gethomepage.dev/icon: readarr.png
          gethomepage.dev/description: Book & Manga Downloads
          gethomepage.dev/widget.type: readarr
          gethomepage.dev/widget.url: http://readarr.media
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_READARR_API_KEY}}` }}"
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    serviceMonitor:
      app:
        serviceName: readarr
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 5m
            scrapeTimeout: 1m
    persistence:
      config:
        existingClaim: *app
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: ${NAS_IP}
        path: /mnt/main/media
        globalMounts:
          - path: /media
