apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: gatus-secret
    template:
      engineVersion: v2
      data:
        SECRET_DOMAIN: ${SECRET_DOMAIN}
        # PUSHOVER_TOKEN: "{{ .GATUS_PUSHOVER_TOKEN }}"
        # PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .GATUS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .GATUS_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPERUSER_PASSWORD }}"
  dataFrom:
    - extract:
        key: POSTGRES
    - extract:
        key: gatus
    # - extract:
    #     key: pushover
