---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.21@sha256:0e8b38452916f7088c07c6b6ddc79ec0d12cad5c1eef6f3156d3c3a503a3a55b
  url: oci://ghcr.io/home-operations/charts/tuppr