---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: meilisearch-secret
    template:
      engineVersion: v2
      data:
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: karakeep
