apiVersion: v1
kind: ConfigMap
metadata:
  name: kavita-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: kavita
        group: guarded
        url: http://kavita.media.svc.cluster.local:5000/api/Health
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 5000"
        alerts:
          - type: pushover
