apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: go2rtc-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        go2rtc.yaml: |
          api:
            origin: '*'
          streams:
            doorbell: {{ .RTSP_DOORBELL }}
            doorbell_2w: {{ .RTSP_DOORBELL_2W }}
            doorbell_sub: {{ .RTSP_DOORBELL_SUB }}
            camera1: {{ .RTSP_CAMERA1 }}
            camera1_sub: {{ .RTSP_CAMERA1_SUB }}
            mechanical: {{ .RTSP_MECHANICAL }}
            mechanical_sub: {{ .RTSP_MECHANICAL_SUB }}
  data:
    - secretKey: RTSP_CAMERA1
      remoteRef:
        key: RTSP_CAMERA1
    - secretKey: RTSP_CAMERA1_SUB
      remoteRef:
        key: RTSP_CAMERA1_SUB
    - secretKey: RTSP_DOORBELL
      remoteRef:
        key: RTSP_DOORBELL
    - secretKey: RTSP_DOORBELL_2W
      remoteRef:
        key: RTSP_DOORBELL_2W
    - secretKey: RTSP_DOORBELL_SUB
      remoteRef:
        key: RTSP_DOORBELL_SUB
    - secretKey: RTSP_MECHANICAL
      remoteRef:
        key: RTSP_MECHANICAL
    - secretKey: RTSP_MECHANICAL_SUB
      remoteRef:
        key: RTSP_MECHANICAL_SUB
