apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: kometa-secret
    template:
      engineVersion: v2
      data:
        KOMETA_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        KOMETA_TRAKT_CLIENT_ID: "{{ .TRAKT_CLIENT_ID }}"
        KOMETA_TRAKT_CLIENT_SECRET: "{{ .TRAKT_CLIENT_SECRET }}"
        KOMETA_TRAKT_ACCESS_TOKEN: "{{ .TRAKT_ACCESS_TOKEN }}"
        KOMETA_TRAKT_REFRESH_TOKEN: "{{ .TRAKT_REFRESH_TOKEN }}"
        KOMETA_TRAKT_CREATED_AT: "{{ .TRAKT_CREATED_AT }}"
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: trakt
