apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: kometa-secret
    template:
      engineVersion: v2
      data:
        KOMETA_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
  dataFrom:
    - extract:
        key: plex
