apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: kometa-secret
    template:
      engineVersion: v2
      data:
        KOMETA_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        KOMETA_TMDB_API_KEY: "{{ .TMDB_API_KEY }}"
        KOMETA_TRAKT_CLIENT_ID: "{{ .TRAKT_CLIENT_ID }}"
        KOMETA_TRAKT_CLIENT_SECRET: "{{ .TRAKT_CLIENT_SECRET }}"
        KOMETA_TRAKT_ACCESS_TOKEN: "{{ .TRAKT_ACCESS_TOKEN }}"
        KOMETA_TRAKT_REFRESH_TOKEN: "{{ .TRAKT_REFRESH_TOKEN }}"
        KOMETA_TRAKT_CREATED_AT: "{{ .TRAKT_CREATED_AT }}"
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: PLEX_TOKEN
    - secretKey: TMDB_API_KEY
      remoteRef:
        key: TMDB_API_KEY
    - secretKey: TRAKT_CLIENT_ID
      remoteRef:
        key: TRAKT_CLIENT_ID
    - secretKey: TRAKT_CLIENT_SECRET
      remoteRef:
        key: TRAKT_CLIENT_SECRET
    - secretKey: TRAKT_ACCESS_TOKEN
      remoteRef:
        key: TRAKT_ACCESS_TOKEN
    - secretKey: TRAKT_REFRESH_TOKEN
      remoteRef:
        key: TRAKT_REFRESH_TOKEN
    - secretKey: TRAKT_CREATED_AT
      remoteRef:
        key: TRAKT_CREATED_AT
