---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.27.0
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  install:
    crds: Skip
    remediation:
      retries: 3
  interval: 30m
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      retries: 3
      strategy: rollback
  values:
    backend:
      replicas: 0
    chunksCache:
      enabled: false
    deploymentMode: SingleBinary
    gateway:
      replicas: 0
    loki:
      analytics:
        reporting_enabled: false
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      compactor:
        delete_request_store: filesystem
        retention_enabled: true
        working_directory: /var/loki/compactor/retention
      ingester:
        chunk_encoding: snappy
      limits_config:
        retention_period: 14d
      schemaConfig:
        configs:
          - from: '2024-04-01'
            index:
              period: 24h
              prefix: loki_index_
            object_store: filesystem
            schema: v13
            store: tsdb
      server:
        log_level: info
      storage:
        type: filesystem
    lokiCanary:
      enabled: false
    read:
      replicas: 0
    resultsCache:
      enabled: false
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      rules:
        searchNamespace: ALL
    singleBinary:
      persistence:
        enabled: true
        size: 50Gi
        storageClass: ceph-block
      replicas: 1
    test:
      enabled: false
    write:
      replicas: 0
