---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-exporter-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: opnsense-exporter-secret
    template:
      engineVersion: v2
      data:
        OPNSENSE_API_KEY: "{{ .OPNSENSE_API_KEY }}"
        OPNSENSE_API_SECRET: "{{ .OPNSENSE_API_SECRET }}"
  data:
    - secretKey: OPNSENSE_API_KEY
      remoteRef:
        key: OPNSENSE_API_KEY
    - secretKey: OPNSENSE_API_SECRET
      remoteRef:
        key: OPNSENSE_API_SECRET
