---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shibari-platform-gatus-ep
  namespace: shibari-platform
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "web-shibari"
        group: shibari-platform
        url: "https://shibari.${SECRET_DOMAIN}/"
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 10000"
        alerts:
          - type: pushover
      - name: "web-queer"
        group: shibari-platform
        url: "https://queer.${SECRET_DOMAIN}/"
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 10000"
        alerts:
          - type: pushover
