apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: unpoller-secret
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_USER: "{{ .UNPOLLER_USERNAME }}"
        UP_UNIFI_DEFAULT_PASS: "{{ .UNPOLLER_PASSWORD }}"
  data:
    - secretKey: UNPOLLER_USERNAME
      remoteRef:
        key: UNPOLLER_USERNAME
    - secretKey: UNPOLLER_PASSWORD
      remoteRef:
        key: UNPOLLER_PASSWORD
