apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: unpoller-secret
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_USER: "{{ .USERNAME }}"
        UP_UNIFI_DEFAULT_PASS: "{{ .PASSWORD }}"
  dataFrom:
    - extract:
        key: unpoller
