---
apiVersion: v1
data:
  ADGUARD_IP: 192.168.5.2
  EMQX_LB: 192.168.5.21
  GO2RTC_LB: 192.168.5.22
  NAS_IP: 192.168.5.10
  OPNSENSE_IP: 192.168.5.1
  PLEX_IP: 192.168.5.172
  POSTGRES_LB: 192.168.5.23
  SKYLAB_IP: 192.168.5.5
  TIMEZONE: America/Denver
  UNIFI_LB: 192.168.5.25
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
