apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    BITWARDEN_ORG_ID: ENC[AES256_GCM,data:lxH2YqGrotwzlSP0kAJDUj4TbjJynNXatRkLuxHW+YA0KM/E,iv:RYpuAz4VvV3jnmvILUr2/VWvav5NmvnpBhyom4oDWuc=,tag:F0YX+sEJI0KujRjnXQdwWw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1Sy2hetTbC7ZRzSwpw==,iv:5IQQNNUDDH9YCTY4q1a+vg3t6NUPU19hO2kpoQcpDcw=,tag:Y4mJ69ZFu2mK2vPhANEyFA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:dFaG3uUD+jsYsGqsz6xB4HXy,iv:+I1EVr+s8Tj+hfwpiDTmUalynt5kCu47zJzOut9GA9I=,tag:RTxhAG97mlv6Q+8k+SHwaA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:+isdsbydmKpkFxgHtfMNujqXqOdoDjGp5hKwmR6TS7Y+z2Wq,iv:4ilKdPMHk9yVSmEjjlke2HJWfkOqHcstj4vN+KKHcO8=,tag:jUcZjtcbHHA3lQ71lESvkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQm16ZjRFa0xaWGt5cUlR
            WVBYUjhkK1hvaTVCeEdCK1RXTHd0UVZwRVJRCnNiUzNQdkVRVXFLT0FmU1EzZW1K
            SXF3bnQxTmJoelVNeG92VTc4THNHRFkKLS0tIGM1V0w2UERzOVRZY1VqQnR6OEIw
            bmptWHFHa1RkWERoVzhXZVlCMW9xdlkKsNs05vY6WWB90xzctwLSz9X9mn5JYYa9
            d+6UFMw66m15c0jumDDt/RWtCIXoTdstDIYoJkmFtCnnsBBM9pgGvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T09:00:36Z"
    mac: ENC[AES256_GCM,data:5BCzA0bas2kojddFShkgQIYqRW8cn/7AFncJwjUXP1tdNAdj7V8KgVdR656RgYLDJ++7wn/iodhKI1psaUVNiIv7TeSo9ZcBK7U7++HEeJVAK7MzmJ64SQeKSztZv8PBfhcO6eicaSY1DxN2EYiIxLHpm1qoXcpy9502vATsDfM=,iv:uUIn/XK1pJn6cc2jB8ClM+C0F0+dZ7d9qwZxls88+/I=,tag:6f2VuqQAeT5h7h5cbxityQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
