apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BEuW1HLL6Ab0IdR47g==,iv:5kly4T/L5XFYykoegBGTYoIxgQ5Ok1/dX7KtqPDay9w=,tag:QMy/sTOtifDn37EO4urb1w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:t9tBqDLbcDFA4/AWsJ1PXNMY,iv:hbTY1dgT6VIN1iR/CBUbW+TMrjU7Pt0vwDM32BRweG8=,tag:Db7umeB3cGB3FuGmfumF6g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:QCc62MkFI2Xfump693zSlBcFQ73G5Te+nY/+EYCuPJKPKBGo,iv:PPPt83us877Y8ion3ks2M4J8klWKdjHhFN5xfHv0jcM=,tag:okIV+Mq1tTCjkht9Ekd4Aw==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:7DRy41TNN42rCdA4CA==,iv:9m/ouu11sOFFhpa53RHbTZFgRJMN18bppGio7XqBMZU=,tag:w0AkiimLV/zWL3nSojslhA==,type:str]
    SECRET_NFS_MINIO: ENC[AES256_GCM,data:HBWmu+c2tut/2dSYH6+c,iv:bvBr+cr/HeedmzLkPMSsRNthUv4+WNMgaNH+ca6i7Q0=,tag:WsdgStfFlQu04mLl9lcXxA==,type:str]
    TIME_ZONE: ENC[AES256_GCM,data:IqPH4MhIMEryilOyvu4=,iv:NYJFG1TzT6/fOfcoVRwjZagrrnkNjqK81eBdQLxcPqM=,tag:66iEJKV3JuR9cu8cdb10sQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmFwNjJrNExSTk9rR1RM
            UjhWZ1p0eTRsWVh2RjcwOWFuQUZDN0dTTzJrCmtvYSt5RXp4dTR0T0JpaFV6RHlr
            cnBSZE44bEVHWjU3WCtNbGtKNWEyVzQKLS0tIHhCdXFES3ZPYzNVbFQyWldSRC9q
            SnZVRVBDeWFlcGtOei9hS0dqdWFIdFEKFVdJnp/x6635lkyDwLU7yuYfVMwkwitu
            H6LPNYa9/fOyFESh5QnGCmIQ62R5ncGlio1rMMpCsy7xlXsk6JaALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T14:09:00Z"
    mac: ENC[AES256_GCM,data:vytgAn9g2gz8DEVHNYrHwfUVTSxRNCjKzhyG2ccL9AtH16NPazcQP9yaVT8mAu6rQ8aiKstn+Gfr83qATGIG05MBsWct1e9NhexML09Tn0pu1bHputHIcjmNK5bz2mOQIS/wTAIU3XEQ4ndpEZbFdoiljgMkPBtkITkD/crSRmM=,iv:NfMp2iaVtlYF1/uzKDhMY572m4AK/zQayu5ovA11z0g=,tag:P4kNhrOc0+8UxuhUD4nH0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
