apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    BITWARDEN_ORG_ID: ENC[AES256_GCM,data:lxH2YqGrotwzlSP0kAJDUj4TbjJynNXatRkLuxHW+YA0KM/E,iv:RYpuAz4VvV3jnmvILUr2/VWvav5NmvnpBhyom4oDWuc=,tag:F0YX+sEJI0KujRjnXQdwWw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1Sy2hetTbC7ZRzSwpw==,iv:5IQQNNUDDH9YCTY4q1a+vg3t6NUPU19hO2kpoQcpDcw=,tag:Y4mJ69ZFu2mK2vPhANEyFA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:dFaG3uUD+jsYsGqsz6xB4HXy,iv:+I1EVr+s8Tj+hfwpiDTmUalynt5kCu47zJzOut9GA9I=,tag:RTxhAG97mlv6Q+8k+SHwaA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:+isdsbydmKpkFxgHtfMNujqXqOdoDjGp5hKwmR6TS7Y+z2Wq,iv:4ilKdPMHk9yVSmEjjlke2HJWfkOqHcstj4vN+KKHcO8=,tag:jUcZjtcbHHA3lQ71lESvkw==,type:str]
    CLUSTER_CIDR: ENC[AES256_GCM,data:pfwu516zpNlEy104,iv:59DNbunUvWrTuykj2Kvnr07c8u3S4glkFRAGCVZxZBM=,tag:wGyBC+oE0HhJBXjg8WBx5Q==,type:str]
    NODE_CIDR: ENC[AES256_GCM,data:e6LpIpPALXldpIRpgdw=,iv:lvtwRIK8j2wFnWspzopfGK1J5qasRahH26T17KmKr38=,tag:VtCsMu3uEBtc6j7F1BlpUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQm16ZjRFa0xaWGt5cUlR
            WVBYUjhkK1hvaTVCeEdCK1RXTHd0UVZwRVJRCnNiUzNQdkVRVXFLT0FmU1EzZW1K
            SXF3bnQxTmJoelVNeG92VTc4THNHRFkKLS0tIGM1V0w2UERzOVRZY1VqQnR6OEIw
            bmptWHFHa1RkWERoVzhXZVlCMW9xdlkKsNs05vY6WWB90xzctwLSz9X9mn5JYYa9
            d+6UFMw66m15c0jumDDt/RWtCIXoTdstDIYoJkmFtCnnsBBM9pgGvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T09:55:43Z"
    mac: ENC[AES256_GCM,data:mCKhy/zF8HehF8Q4DubuER/vkk3U60Sx70vrJ0szyO6JH8aXhsKw8M6Ej0G4wl5ZWpeb+CrI6y6QaIhDtNJnitMA7bBBpL5ebRjLg/TE+GJoxa12eT1U07ZCtXOgeb1LIeiymd2d7tIxxkBwdy+tlJzZv4/RsQdjpQtr8J5/Gg4=,iv:LlHT2wlZ9tOySk7236RaUzBOotEkfra5EhyUjbTu6hg=,tag:zHpcXSU+vubV4uMm4LysqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
