---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app shibari-platform-dev
  namespace: flux-system
spec:
  targetNamespace: shibari-platform-dev
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: platform-x-club-source
    - name: shibari-platform-dev-network-policies
    - name: cloudnative-pg
    - name: dragonfly-operator
    - name: external-secrets-stores
  path: ./kubernetes/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-x-club
  wait: true
  interval: 30m
  timeout: 10m
  postBuild:
    substitute:
      ENV: dev
      BWS_PREFIX: SHIBARI_DEV
      DNS_TARGET: external.${SECRET_DOMAIN}
      DOMAIN_SHIBARI: shibari-dev.${SECRET_DOMAIN}
      DOMAIN_QUEER: queer-dev.${SECRET_DOMAIN}
      DOMAIN_PROMO_SHIBARI: shibari-promo-dev.${SECRET_DOMAIN}
      DOMAIN_PROMO_QUEER: queer-promo-dev.${SECRET_DOMAIN}
