---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-ota
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: zigbee2mqtt-ota-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MQTT_USER: "{{ .Z2M_EMQX_USERNAME }}"
        MQTT_PASS: "{{ .Z2M_EMQX_PASSWORD }}"
  dataFrom:
    - extract:
        key: EMQX
