apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homebox-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        HBOX_DATABASE_DATABASE: &dbName homebox
        HBOX_DATABASE_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        HBOX_DATABASE_PORT: "5432"
        HBOX_DATABASE_PASSWORD: &dbPass "{{ .HOMEBOX_POSTGRES_PASSWORD }}"
        HBOX_DATABASE_USERNAME: &dbUser "{{ .HOMEBOX_POSTGRES_USER }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPERUSER_PASSWORD }}"
  dataFrom:
    - extract:
        key: homebox
    - extract:
        key: POSTGRES
