apiVersion: v1
kind: Secret
metadata:
    name: homebox-pepper
    namespace: default
type: Opaque
stringData:
    HBOX_AUTH_API_KEY_PEPPER: ENC[AES256_GCM,data:m096Tq9BqJuvmUYG9gdh+zQLf3EMCcX6gSarcuNOO/nqtWKnxaAzyfQJAq7TX2Ufy9keIcZdek5uOrcYqpOGEQ==,iv:YPQ2HCbfwQNjv5h2FCZXtdA0ndPTlVUVf30cmfl2orI=,tag:REjUcqphhJcyegjr0MQyqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbk5VZ1c0SUJUMU9Ma0R5
            enB0UEV2RVVvb1lqMHVlWTd6VFpmSFp3aDAwCjZXaTlvQ0hzQXlySlhFMDNQZWl6
            M21XUlhLRWQ0UUpCRGpwdk9LNzJZU1kKLS0tIE1hREVXMllZWm5jSnFFMjhqbm1Q
            SVg3VzhXRjgxWGphWmZBeFRmY1dVUDgKmBQSxdfR5gWzSSyG5P/NMbjOVh07XOmQ
            3CQzksfn0XMKILILsbE7AoQjVWsW0T7pDrfb15zTjJHLsZeDZQKa9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T04:40:49Z"
    mac: ENC[AES256_GCM,data:KUjJM4KJqG45nZd7F2J2ZV5nvN3dACX+UKNvKJrXYLI98Ujfn2F2ZaOPAwxWWaYbUwx94lRTmCleMpQr8xSrKltbqj7KZjIyw3OvG4/g2HMTlqAMTeLhkqBRYnP82l0KkX4/MI5WgyiDa4VIpHlaBWkiOtHmpw5Ugcgx4w/KZQs=,iv:kDyZYkOo3pe17CBxa7RWmUCB+F++zi4HvvNhsZjT1LM=,tag:MIlXrh4lEG6GeXTAnb94ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
