#!/usr/bin/env bash
# Generate repository structure overview for agents
# Usage: ./generate-repo-map.sh

set -euo pipefail

echo "# Repository Structure Map"
echo ""
echo "Generated: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""

echo "## Namespaces and Applications"
echo ""
echo "| Namespace | Applications | Count |"
echo "|-----------|--------------|-------|"

for namespace_dir in kubernetes/apps/*/; do
    if [ -d "$namespace_dir" ]; then
        namespace=$(basename "$namespace_dir")
        
        # Skip if namespace.yaml or kustomization.yaml
        if [ "$namespace" = "namespace.yaml" ] || [ "$namespace" = "kustomization.yaml" ]; then
            continue
        fi
        
        # Count apps (directories with ks.yaml)
        app_count=$(find "$namespace_dir" -maxdepth 2 -name "ks.yaml" 2>/dev/null | wc -l)
        
        # List apps
        apps=$(find "$namespace_dir" -maxdepth 2 -name "ks.yaml" -exec dirname {} \; 2>/dev/null | xargs -I {} basename {} | sort | tr '\n' ', ' | sed 's/,$//')
        
        if [ $app_count -gt 0 ]; then
            echo "| \`$namespace\` | $apps | $app_count |"
        fi
    fi
done

echo ""
echo "## Helm Repositories"
echo ""
echo "| Repository Name | URL |"
echo "|-----------------|-----|"

if [ -d "kubernetes/flux/repositories" ]; then
    for repo_file in kubernetes/flux/repositories/helm/*.yaml; do
        if [ -f "$repo_file" ]; then
            name=$(yq eval '.metadata.name' "$repo_file" 2>/dev/null || echo "unknown")
            url=$(yq eval '.spec.url' "$repo_file" 2>/dev/null || echo "unknown")
            if [ "$name" != "unknown" ] && [ "$name" != "null" ]; then
                echo "| \`$name\` | $url |"
            fi
        fi
    done
fi

echo ""
echo "## Storage Classes"
echo ""
if command -v kubectl &> /dev/null && [ -f "${KUBECONFIG:-}" ]; then
    echo "| Storage Class | Provisioner |"
    echo "|---------------|-------------|"
    kubectl get storageclass -o custom-columns=NAME:.metadata.name,PROVISIONER:.provisioner --no-headers 2>/dev/null | while read -r name provisioner; do
        echo "| \`$name\` | $provisioner |"
    done
else
    echo "⚠️  Cluster access not available. Common storage classes:"
    echo "| Storage Class | Use Case |"
    echo "|---------------|----------|"
    echo "| \`ceph-block\` | Single-pod block storage |"
    echo "| \`ceph-filesystem\` | Multi-pod shared storage |"
    echo "| \`openebs-hostpath\` | Node-local storage |"
fi

echo ""
echo "## Directory Structure"
echo ""
echo "\`\`\`"
tree -L 3 -I '.git|node_modules|dist|build' --dirsfirst -a \
  --charset ascii \
  -I '*.log|*.tmp|kubeconfig|age.key|.venv|.terraform' \
  . 2>/dev/null || find . -maxdepth 3 -type d | grep -v ".git" | sort
echo "\`\`\`"

echo ""
echo "## Statistics"
echo ""
echo "- **Total Applications**: $(find kubernetes/apps -name "ks.yaml" | wc -l)"
echo "- **Total Namespaces**: $(find kubernetes/apps -maxdepth 1 -type d | grep -v "^\.$" | wc -l)"
echo "- **HelmReleases**: $(find kubernetes/apps -name "helmrelease.yaml" | wc -l)"
echo "- **ExternalSecrets**: $(find kubernetes/apps -name "externalsecret.yaml" | wc -l)"
echo "- **PVCs**: $(find kubernetes/apps -name "pvc.yaml" | wc -l)"
echo "- **ServiceMonitors**: $(find kubernetes/apps -name "servicemonitor.yaml" | wc -l)"
echo ""
echo "---"
echo "Generated by: \`scripts/generate-repo-map.sh\`"
