apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: appuser-secret
  labels:
    cnpg.io/reload: "true"
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: appuser-secret
  map:
    - bwSecretId: b688f227-c5f4-489d-a5ea-b18e00a3c99f
      secretKeyName: password
    - bwSecretId: eb5fe5c0-c033-4dec-bf80-b18e00a3b649
      secretKeyName: username
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
