apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: aws-secret
  labels:
    cnpg.io/reload: "true"
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: aws-secret
  map:
    - bwSecretId: 344fdb3b-57cc-477e-9b6c-b18d0141c611
      secretKeyName: POSTGRES_AWS_ACCESS_KEY
    - bwSecretId: dc28e79d-d944-4e64-9387-b18d0141e2ff
      secretKeyName: POSTGRES_AWS_SECRET_KEY
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
