apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    labels:
        cnpg.io/reload: "true"
data:
    username: ENC[AES256_GCM,data:cE7SG13jYbyhj8g=,iv:+Zlgt9YhXJOY49JU31MHIIFwwOJKf2b/pIFTRD5alaE=,tag:nuxuMt/YLZtWEbRX/0KwLg==,type:str]
    password: ENC[AES256_GCM,data:dE8oia4vhTP58GBM9DVYU90d/DtLdrfNASy0fHe9IGVhnQqczUQRh2b7hSLZrewsAKVyoyOJOYLMmnAf5BuVSQ==,iv:Jnaiqxe+peTTYEBVWLduHSgqMSejAfRoIxyRN7Csr/4=,tag:Va/mVYobyIsGQkGydJ6eVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmFwNjJrNExSTk9rR1RM
            UjhWZ1p0eTRsWVh2RjcwOWFuQUZDN0dTTzJrCmtvYSt5RXp4dTR0T0JpaFV6RHlr
            cnBSZE44bEVHWjU3WCtNbGtKNWEyVzQKLS0tIHhCdXFES3ZPYzNVbFQyWldSRC9q
            SnZVRVBDeWFlcGtOei9hS0dqdWFIdFEKFVdJnp/x6635lkyDwLU7yuYfVMwkwitu
            H6LPNYa9/fOyFESh5QnGCmIQ62R5ncGlio1rMMpCsy7xlXsk6JaALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T14:14:07Z"
    mac: ENC[AES256_GCM,data:/8L8X0iGF6LV4DLRE4Lv40v12eMBG6kRfOdDz3FcYKYzIBJM9B9VgS/jypeufA4gD6ndgiWBmKCjcOv6JA6hguqHgfI+FHIJ8bobgsgn9X6JTwVssALF15wdlFV0TXPw/4mKKhnU+y1EOmI/BkNvCW2k9eXkqHfarbMk9f/tgY0=,iv:pRFhtEmgRDAu5zIHTnPKtRoujtiByqDD4RnroQ0kikY=,tag:h0KVyWwl6CZ8nbnlD/4acw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
