apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    dbname: ENC[AES256_GCM,data:/OQOicv60QA=,iv:G9S8lfZrfxoWFp93UnDfPwF2ItPExgGUkKEfJGdnHC0=,tag:V4eXsn7XEUPDwcfX2mDhLw==,type:str]
    username: ENC[AES256_GCM,data:JLsP/flw9Empsf4=,iv:AJiU0tZIVM1qT/nDvQLnzL/ZYpMHS2OSDy+5ExE54c0=,tag:v+odBTzEalHm3JrvudzTAw==,type:str]
    password: ENC[AES256_GCM,data:2d56UIG8xbf5kd3lOiBsqM3PqG6gMFmb3sLGmuE885C3XHdKMa0hrAdSYiN6OmJmFKHvgSRN1l19J+JHFSP8+g==,iv:1RyYwvvBJ3Wxk5ZQtpVZ2StB3qT49R7jh8ssFpzup9U=,tag:zPe7+rdBUIANNEESHowv1w==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmFwNjJrNExSTk9rR1RM
            UjhWZ1p0eTRsWVh2RjcwOWFuQUZDN0dTTzJrCmtvYSt5RXp4dTR0T0JpaFV6RHlr
            cnBSZE44bEVHWjU3WCtNbGtKNWEyVzQKLS0tIHhCdXFES3ZPYzNVbFQyWldSRC9q
            SnZVRVBDeWFlcGtOei9hS0dqdWFIdFEKFVdJnp/x6635lkyDwLU7yuYfVMwkwitu
            H6LPNYa9/fOyFESh5QnGCmIQ62R5ncGlio1rMMpCsy7xlXsk6JaALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-30T06:45:50Z"
    mac: ENC[AES256_GCM,data:sUXCHa0sZBvhAo52DtpnTUcHl29f6d8CfKPvx9NZAW7pmdZ11dHsCZgv5NOaVP0XvN5lUX/jJNTg01wiUvPlp5CjXJPp14fxRCpKR7FjR5QrPfR2wJ8fwpqDtr+O0jmlG694ph92IoyEYJQIThL3mmczGH7K7z+jkmoGz4MOrQk=,iv:2rky3iPs1+8JQBNZqlGX67PULTYv5b3/5XznZhTXhCM=,tag:UeYX3fD3GKMjmUfr6jvd9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
