apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: superuser-secret
  labels:
    cnpg.io/reload: "true"
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: superuser-secret
  map:
    - bwSecretId: 8a5322e7-77b3-4948-9698-b18d01425943
      secretKeyName: password
    - bwSecretId: fb22595b-7586-4b39-8f5d-b18d01422bee
      secretKeyName: username
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
