---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-exporter-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: adguard-exporter-secret
    template:
      engineVersion: v2
      data:
        ADGUARD_USERNAME: "{{ .ADGUARD_USERNAME }}"
        ADGUARD_PASSWORD: "{{ .ADGUARD_PASSWORD }}"
  data:
    - secretKey: ADGUARD_USERNAME
      remoteRef:
        key: ADGUARD_USERNAME
    - secretKey: ADGUARD_PASSWORD
      remoteRef:
        key: ADGUARD_PASSWORD
