---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: 6.17.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: promtail
    config:
      clients:
        - url: http://loki-headless.observability.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
          - match:
              selector: '{app=~"ingress-nginx.*"}'
              stages:
                - json:
                    expressions:
                      status: status
                      method: method
                - labels:
                    status:
                    method:
          - match:
              selector: '{namespace="flux-system"}'
              stages:
                - json:
                    expressions:
                      level: level
                - labels:
                    level:
          - match:
              selector: '{namespace="rook-ceph", container="rook-ceph-operator"}'
              stages:
                - json:
                    expressions:
                      level: level
                - labels:
                    level:
          - match:
              selector: '{app="homebox"}'
              stages:
                - json:
                    expressions:
                      level: level
                - labels:
                    level:
    serviceMonitor:
      enabled: true
  driftDetection:
    mode: enabled
