apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:w/1lMzyWPzMp/tXL3hxPD+ejqCCvCATiTH6wUjf0tyE=,iv:smOjt+I5CpWp+rCEp8UMIid7cQl0U5kMbahdqdMyRwY=,tag:r2N+uzdpqCFoykUoPBi+bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdG5NVXB4c2o0b1orMnBq
            M1BGcDJhT1N2VFc1djdaWDg2Zm4vOWl3MTJFCjBwKzV6WWlNcGNmTDRXVDhNUTRI
            WnhicmM0Z0MyMlZqTWdRSzBzMDlFSXcKLS0tIHVxQXlYSGJ5UWhCcEhpNDdOMHM4
            bXJjSVkvd2ptUTROR3JZM2dRenJhblEKNbiV/w+hjlYLJCAYfjkHghFHcxGJIYOr
            C/uD25b7ZdRo1x/jPB3MqrMs8x3zDd4jMBE11zlsBrUJlKc50SZtxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T08:25:48Z"
    mac: ENC[AES256_GCM,data:ZxxfhEdt0q7gb8YS7JF2zUqMdJKkxAHplMpS+1Y40jfIihdBA6RabcLMGOsZlIv4WjBABQUNmCJRJUB0KzM91Gqasgef3r1T5jX3OSFTPI4fBkslF/kK3sqYnsYi4ICpZsxYVWAclDbXX0PId2XAYUC55VHjtjAjiIMMEeD5QUc=,iv:u33ciN9DRDw41FMyoJIUS96LQrfBuU/mtvIKrQwBkDc=,tag:O0CSq/w9WQ2gwSs8wiH+IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
