apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:9h+yCzjwE7XdRqFuXTD1Nkza2tNe0QQbigkGBnng1R4=,iv:efeYbr0WB1ak4MwDHXbaCceb2UcuqJ9AGl3/TQLPNOs=,tag:9ZNa7TBDImnL2IhOAVZIjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU0QvTHhoMzdTZ2lKcU9F
            WXVwbE5IMEQzcEhsT3d3bUJ2ajV2QmpvRlJBCnJCZ3gyeW14WTROcVZEMEkreFVL
            OE5qMi9EdENpQUwvaWpRQ2drWkJYL28KLS0tIDBEckV5VklRTU13RkEzZjd5OHBK
            N0F0bHRrZHp4MjBWWjI1ZHRHYnVIejQKfrffSeXR2i76fD1oXWTsSXF94ILUjB5s
            pTmC53rRV4qqHAtUel2l0bV//YvArf7E3JL1dreDDe3vUFH+uh2ZCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T01:49:08Z"
    mac: ENC[AES256_GCM,data:OYbxIEprf1bpynT4yE7bm8pmeMSf3EIYeAQWRBOnjyrCi1YZd3vsdj8mFC9MNRAdbGl4TfZl6uSNH4a0YkBNc7JGafgGnKpSEiNdRr+fECzEvdvo8koCxtWUMO61vgbIaUHYI3ZFm24Fle1e+O9xV0btQlbtqA3I5iqAP0BZpyY=,iv:vj3LvIDxRZiYMFr5yN6QLmMTuPKKX/L7wkhUbAeQEyQ=,tag:6ksDGFVqxSjMSSYYuKcjkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
