apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:htYywWI8onZjokz2dT0SRMP7KAhv1kr1g14MhspljLw=,iv:yEkI+nznk+9F3VQhHe1rTcUaC2fHu3mMRfot8VJfEpo=,tag:Bad4+CH0/p2GYMYRaMjDpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d2xqODVOVm9CRFhSY1lN
            aXdBcWJUVStITmNXYWZiRUhhQXJzalF1NXpZCnlBUFRWRGNoc2pONjdER3Zxbkhw
            RHdxT0RDRVh5MWg5V3NDU3pWVVJsUTgKLS0tIEtyVzhiUGNSakZSdytMUSsvVHlq
            bHVVazVBTElJU1ZTdE1EbERXZU1icFUKM+WUX4LT2Te52wJO0bMN4LelsDym/NTm
            Y5fKIF8GbukHlsG0ZDSEDMKzyY+oVA4VUtftB9IwvWLnw+IWjYFdwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T06:44:00Z"
    mac: ENC[AES256_GCM,data:SfXXhqT4syx3xq7BzwLxDoxaPt1mwBwb01nm/QNIeJv2tWsHLgfYIrDQp2SpUBmAI47BRFuVmIKTYW0/YAEuRm904I3i7+s2lgQB8AuF+VU9080EZYV4b628Xk1eRSJO/VviP3q9CnOZU0ShytfoKxGmJUNnMvxu2ouYoT5Zado=,iv:BOhkZfrN8zvIsob5prRQLe5C9+HJIWadIltYU3aE37E=,tag:1HTWoiBY95epzHzNGOWzug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
