apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:3ynTB+2hPYS6JHoo+B+KnneqYVl1Q7Chm+fNlkDEpF4=,iv:qVBEA79dnDrRQ0Z15Hzmo2HfkbhjP56kfb1L4P0OOKI=,tag:qXjXKHehWBHBDLhZLv0YKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM1lNS1hOTHVEUDFhQUdv
            dnRZeU5nMDFTNkg4bUVWa3RxbFpJcHJxNmlFCmZ0THU0NzJFcjVlNUVrYmFXRzRV
            dk9ucitNUkxkMVo3RDRuaTZvbHlmM28KLS0tIGtCYnJKeUVzTzU2RWR4SnVzSU0y
            YkJ4ekNHSU1zTUZCTnJwZGcvbG5LSzQKGqzyHE2L5lVNfJsjT/M1SlxI6RFYX8kb
            xO0HoYkazSyaOLNjXvQ6T+j+YThSb8EfIomJsV8FNdbwDxoO5SDAyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T23:30:16Z"
    mac: ENC[AES256_GCM,data:fhbAqjD+Rnekw0EaKIpA2Bjr21EfpD4hJWnqKAOMQ1cRzvOG+mBXOebDY8VQraBgeAOEbt3oV0ssDuFwBr9zZfjwoDQZTpM0QhzDXDtYWgmr8Jt3FM0iwW7dUjUuKoTt1a/Qb6I729G7j54/umbO+8CG8bnpirVqEnn1XPbC5EY=,iv:kVn+l1CnNlQVAJkCEbdMr5rYq+JaH4lplLHd7FIwfbM=,tag:q5nwQHr+mnygz1HJdrcwcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
