apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mealie-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: &dbName mealie
        POSTGRES_SERVER: &dbHost postgres16-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_PASSWORD: &dbPass "{{ .MEALIE_POSTGRES_PASSWORD }}"
        POSTGRES_USER: &dbUser "{{ .MEALIE_POSTGRES_USER }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPERUSER_PASSWORD }}"
  dataFrom:
    - extract:
        key: mealie
    - extract:
        key: POSTGRES
