apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_API_KEY }}"
        HOMEPAGE_VAR_PORTAINER_TOKEN: "{{ .PORTAINER_TOKEN }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .HOMEPAGE_UNIFI_USER }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .HOMEPAGE_UNIFI_PASS }}"
        HOMEPAGE_VAR_TRUENAS_USER: "{{ .HOMEPAGE_TRUENAS_USER }}"
        HOMEPAGE_VAR_TRUENAS_PASS: "{{ .HOMEPAGE_TRUENAS_PASS }}"
        ## Default
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HASS_TOKEN }}"
        # HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .HOMEPAGE_VAR_PAPERLESS_TOKEN }}"
        ## Downloads
        HOMEPAGE_VAR_AUTOBRR_TOKEN: "{{ .AUTOBRR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        # HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        # HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        ## Observability
        # HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USER }}"
        # HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
  # data:
  #   - secretKey: LATITUDE
  #     remoteRef:
  #       key: LATITUDE
  #   - secretKey: LONGITUDE
  #     remoteRef:
  #       key: LONGITUDE
  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: autobrr
    - extract:
        key: prowlarr
    - extract:
        key: radarr
    - extract:
        key: sonarr
