apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        # Generics
        HOMEPAGE_VAR_LATITUDE: "{{ .LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .LONGITUDE }}"

        ## HASS
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HOMEPAGE_HASS_TOKEN }}"
  dataFrom:
    - extract:
        key: *name
    - extract:
        key: LATITUDE
    - extract:
        key: LONGITUDE
