---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: qbittorrent
    - extract:
        key: autobrr
    - extract:
        key: prowlarr
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: overseerr
    - extract:
        key: bazarr
    - extract:
        key: GRAFANA
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      data:
        HOMEPAGE_VAR_ADGUARD_PASSWORD: "{{ .HOMEPAGE_ADGUARD_PASSWORD }}"
        HOMEPAGE_VAR_ADGUARD_USERNAME: "{{ .HOMEPAGE_ADGUARD_USERNAME }}"
        HOMEPAGE_VAR_AUTOBRR_API_KEY: "{{ .AUTOBRR_API_KEY }}"
        HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_API_KEY }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USERNAME }}"
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HASS_TOKEN }}"
        HOMEPAGE_VAR_MEALIE_API_KEY: "{{ .HOMEPAGE_MEALIE_API_KEY }}"
        HOMEPAGE_VAR_OPNSENSE_PASSWORD: "{{ .HOMEPAGE_OPNSENSE_PASSWORD }}"
        HOMEPAGE_VAR_OPNSENSE_USERNAME: "{{ .HOMEPAGE_OPNSENSE_USERNAME }}"
        HOMEPAGE_VAR_OVERSEERR_API_KEY: "{{ .OVERSEERR_API_KEY }}"
        HOMEPAGE_VAR_PORTAINER_TOKEN: "{{ .PORTAINER_TOKEN }}"
        HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_TRUENAS_PASSWORD: "{{ .HOMEPAGE_TRUENAS_PASSWORD }}"
        HOMEPAGE_VAR_TRUENAS_USERNAME: "{{ .HOMEPAGE_TRUENAS_USERNAME }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .HOMEPAGE_UNIFI_PASSWORD }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .HOMEPAGE_UNIFI_USERNAME }}"
      engineVersion: v2
