apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        # Generics
        HOMEPAGE_VAR_LATITUDE: "{{ .LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .LONGITUDE }}"

        ## HASS
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HOMEPAGE_HASS_TOKEN }}"

        ## Media
        # HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .LIDARR__API_KEY }}"
        # HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR__API_KEY }}"
        # HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR__API_KEY }}"
  dataFrom:
    - extract:
        key: LATITUDE
    - extract:
        key: LONGITUDE
    - extract:
        key: HOMEPAGE_HASS_TOKEN
    # - extract:
    #     key: lidarr
    # - extract:
    #     key: radarr
    # - extract:
    #     key: sonarr
