apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  data:
  - secretKey: HOMEPAGE_VAR_HASS_TOKEN
    remoteRef:
      key: HOMEPAGE_HASS_TOKEN
  - secretKey: LATITUDE
    remoteRef:
      key: LATITUDE
  - secretKey: LONGITUDE
    remoteRef:
      key: LONGITUDE
