apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: homepage-secret
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: homepage-secret
  map:
    - bwSecretId: 34e4da8c-85e4-4d08-a22b-b19300d5f85f
      secretKeyName: HOMEPAGE_VAR_HASS_TOKEN
    - bwSecretId: 179f41e9-2dac-4e33-b158-b18c0151e449
      secretKeyName: HOMEPAGE_VAR_LATITUDE
    - bwSecretId: 4582dc1e-ad0a-438c-b550-b18c0151fa78
      secretKeyName: HOMEPAGE_VAR_LONGITUDE
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
