---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../templates/network-policies/default-deny
  - ../../../../templates/network-policies/allow-dns
  - ../../../../templates/network-policies/allow-kube-apiserver
  - ../../../../templates/network-policies/allow-intra-namespace
  - ../../../../templates/network-policies/allow-from-nodes
  - ../../../../templates/network-policies/allow-from-ingress
  - ../../../../templates/network-policies/allow-from-monitoring
  - ./ingress-cnpg-operator.yaml
  - ./egress-https.yaml
  - ./egress-rgw.yaml
