---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: frigate-secret
    template:
      engineVersion: v2
      data:
        # EMQX
        FRIGATE_MQTT_USERNAME: "{{ .FRIGATE_EMQX_USERNAME }}"
        FRIGATE_MQTT_PASSWORD: "{{ .FRIGATE_EMQX_PASSWORD }}"
  dataFrom:
    - extract:
        key: EMQX
