apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        HASS_ELEVATION: "{{ .ELEVATION }}"
        HASS_LATITUDE: "{{ .LATITUDE }}"
        HASS_LONGITUDE: "{{ .LONGITUDE }}"
  dataFrom:
    - extract:
        key: home-assistant
    - key: LATITUDE
    - key: LONGITUDE
