apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        HASS_ELEVATION: "{{ .ELEVATION }}"
        HASS_LATITUDE: "{{ .LATITUDE }}"
        HASS_LONGITUDE: "{{ .LONGITUDE }}"
  data:
    - secretKey: LATITUDE
      remoteRef:
        key: LATITUDE
    - secretKey: LONGITUDE
      remoteRef:
        key: LONGITUDE
  dataFrom:
    - extract:
        key: home-assistant
