apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: home-assistant-secret
spec:
  organizationId: ${BITWARDEN_ORG_ID}
  secretName: home-assistant-secret
  map:
    - bwSecretId: d5df6d3c-fdd0-4044-866a-b193008e341f
      secretKeyName: HASS_ELEVATION
    - bwSecretId: 179f41e9-2dac-4e33-b158-b18c0151e449
      secretKeyName: LATITUDE
    - bwSecretId: 4582dc1e-ad0a-438c-b550-b18c0151fa78
      secretKeyName: LONGITUDE
  authToken:
    secretName: bitwarden-secret
    secretKey: access-token
