apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rook-ceph-dashboard-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  data:
  - secretKey: password
    remoteRef:
      key: ROOK_DASHBOARD_PASSWORD
