apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard
data:
    rook-ceph-dashboard-password: ENC[AES256_GCM,data:yswWpCabwau6zzaW7IW4ZI+YIM8rrXKFyPsDx2m2qa2xG7Mh7nTJhnxWmFbBoVhx07eR5vs69++ZvslEhqfApQ==,iv:IBUXMnxtgDUcwlkGB27FAu5XOOkOAFgh+PNHBJjD63g=,tag:Kj9K8S6mbS3wErRP5OihOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmFwNjJrNExSTk9rR1RM
            UjhWZ1p0eTRsWVh2RjcwOWFuQUZDN0dTTzJrCmtvYSt5RXp4dTR0T0JpaFV6RHlr
            cnBSZE44bEVHWjU3WCtNbGtKNWEyVzQKLS0tIHhCdXFES3ZPYzNVbFQyWldSRC9q
            SnZVRVBDeWFlcGtOei9hS0dqdWFIdFEKFVdJnp/x6635lkyDwLU7yuYfVMwkwitu
            H6LPNYa9/fOyFESh5QnGCmIQ62R5ncGlio1rMMpCsy7xlXsk6JaALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T03:22:05Z"
    mac: ENC[AES256_GCM,data:l3RgaAnl5qdxeBQEdnWw0PbhWu9/+teswlIeh4dEQScSdMQq2lL8qqflluJJfaknxaua8Hq3KmHtx3vUUavcdxGXvR6G9QpKzlj5yG11aN2+YWErX7lbv8+JQDYSfi0O983Jg/DbT4zYCuEIm1VMJPVskDBx/VaphuR1bxec4v0=,iv:lMHzET3w0Cxb17/FjyaShsyNwkRge+7fLgXF5iI0c1Y=,tag:s28Dpc2lsD9gZ1xEbRurxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
