apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yQeEKwCHgBWmc0zuzSUATxI9ZNFbAtCVPO7grKeJHn9TyxjxIHqvZQ==,iv:kU8GBQqmnEKSRqQTiPTru9npwqiuqsG5HgoOeoipSFE=,tag:3ifv7stlfa6WyW5Ul7kdwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYWxRWU03Wkc4T09UQ1hJ
            eVlSZkRXYkFZNGRwWHNPSUZpSFE5cVNleDA4Cm1uL0p3cExZY1ZlOUxoR0N2UTVB
            R3RUZDVLWTByMUhZanloT09IZXczcmMKLS0tIDlNUDBYWWRNSnZVbFlFMjZOeW9v
            UnUwTUY1Zk52QUp0YWhWVFJVZUFFS1EKDypYMQ6TTnVuonScTzH9smuC5K6UTGKC
            0cOkGn/9ABLVn4rz7S/43ytYv3kQI/RJUmBgChxaDTfdPbiSiyMaOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-15T08:25:49Z"
    mac: ENC[AES256_GCM,data:a82emZyNKQrzpBtV25i/PNPmib3TAaj/+K5uAjbroNTdl7bk+HBDe+4bboLzJaUsQWX6qfSBh02SDzeIpBBQp26QqxAoUnQhEgfZIoV1Q4O5+68Da+vjfuL3yel/lYBzpUGtRxzxvyLdbYFXKCRbm1/yojZVilSjKv8hC2rClWk=,iv:0yie5z95xkPHHAce24RPb869ec2suqPXRqlkG/feX1I=,tag:O9UhwHnaC6SbRwMs6ICMsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
