apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:pbxQk5j1HEArP7rCZjI06krFj01KCCrnRtdoJ9RByl3JhSy1n9XMBw==,iv:xOCrsqCBGqAR4MP77UgAxhrUNBilYYGP7hLT7HhhUl4=,tag:+jQmwCiSUIZcHDaqB/OZ5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TDFkTklBSFdHbXVmbHNP
            TmFQcnlVV2hwWnQ2eTBJQ3E3RUV5ZHduUlNBClk0Z0cxWkhUY0NDb1cxTDUzSSs3
            aitxV3E5c2ZDMDNyb0NyNUNjb2J2TEEKLS0tIDdGVDROQjhXK0dHNHFRaXU3dG5m
            aWxaOWY4MkVreG0yQ1hWeUNwMDUyR0EKwDER4Mww0zKl0VO2sNtYsdVRkkjTxj9N
            R1GltFan6r+4uWBjmeE+256Sle5It5rvkz2u2Ov/voXDsfIpZcxmkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T23:30:16Z"
    mac: ENC[AES256_GCM,data:V2y33nh59gPb82SbPIbqb1YG+QGfFwaP4oIu4ECdVxm00xNU5w6TVqiODsmgOQ45qv/3jn+NReoBL0/5/uzhNpl2yiBb6icu0fbKUuw0SOkAGIXB52LCdwWpnQA/4PB6myyuSWzYOMr6MAa5jvpRNIhyVO3Dh6W2IZB6SLB8MDM=,iv:YtlAPvKjZeYgoL9cXAVex/NQBRbyh/shmOp97jATR2M=,tag:Jb0iIcihJnYeSROHGFS4yQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
