apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:e/JvImuyww0FKUg1CSxrhOEHMTaYAydweRcPBJh2qemwajPdUm3Wng==,iv:4TphtP2Ys3wLW4C5xfShtulBeEt7be+JO674skuyyp4=,tag:GilOhB8dFeRqLiNfDzfLDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdVBpNTdOcmRCcjcxdVV0
            R1NzQ3ZPcVM4RjB3SXhvZ2JuQitkVUs5bWtFCmRuNTRsNjNnd0tYSS9iSWFON1F1
            Y09CTko1WVd4WkJsUW8rYXY0SVVmL2MKLS0tIEpuUktERnp6Qm5pdEMwQ1BQeTly
            NzJmLzJoaUg1UnhWMXdtZUNhbU1GZ1EKd7p2Q0UhzNMhdTNPid1SmuqjplMZgw2H
            m72/Wc+ilGA8Hv/SbymCOGg0wO5uUaH/xfZ53bSflwRXJg7KhnTXwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T06:44:00Z"
    mac: ENC[AES256_GCM,data:RvYd30GRAyZht/MBUtbbSiDnJVM3EUFqwxCcRC6EyXwDkuHe9zTlpvXMGj4ETOYqLedTy7G8iuxsUJ+tXLPk34wlbxAG5gG7rwziuXYyHGpSD53E8l0bsQr3mg4v06xVZR9ZiMotbxnV679mS36tFVPbiPmdth4JQrbFWjv6Vhs=,iv:it6cF0pEAre2BJ4SuDzhjnm6xBl4LI+OI/K0/lfNY2s=,tag:QYgVPRT2gkYlIyQpPSBdQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
