---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: volsync
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.18.5
    digest: sha256:1f23c55e3a595eac992d568a3bb23934944f553b245d14d5a8bfd5c7e0409eff
  url: oci://ghcr.io/home-operations/charts-mirror/volsync-perfectra1n
