apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: headlamp-oidc-secret
    creationPolicy: Owner
  data:
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: headlamp
      property: OIDC_CLIENT_ID
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: headlamp
      property: OIDC_CLIENT_SECRET
