apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-secret
    annotations:
        replicator.v1.mittwald.de/replicate-to: actions-runner-system, database, default, observability, rook-ceph, storage
stringData:
    access-token: ENC[AES256_GCM,data:GxRRUB3BE3uKNTeK4NcLc82cLFKPNICHIhBZnNxO5gnreXrDNLaTlIYyUMUQXABzYOYtXnB5BJESWNj01LtecJRmfqNJdKTVk1IblBfQLykzMyGsf0FnbraBQyFqoQ==,iv:2b+lSUd3EgM/w/FpwXid7eNaGRIpUHzMmJO2U2+ESik=,tag:qJEXIpDJIugmlhemJ4VLMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmFwNjJrNExSTk9rR1RM
            UjhWZ1p0eTRsWVh2RjcwOWFuQUZDN0dTTzJrCmtvYSt5RXp4dTR0T0JpaFV6RHlr
            cnBSZE44bEVHWjU3WCtNbGtKNWEyVzQKLS0tIHhCdXFES3ZPYzNVbFQyWldSRC9q
            SnZVRVBDeWFlcGtOei9hS0dqdWFIdFEKFVdJnp/x6635lkyDwLU7yuYfVMwkwitu
            H6LPNYa9/fOyFESh5QnGCmIQ62R5ncGlio1rMMpCsy7xlXsk6JaALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T04:24:52Z"
    mac: ENC[AES256_GCM,data:slD7QqH2RY/Tw9mBWRC87uhuvK+F9jXD6+P2sEodfCtv4NLYEMcykV/Leguy2lhECx1Zc9xnHI3XBErWdZ/Uqaxj2ruBFZ1YijnFZm/8A1jzhfsVHQlidSxx8IF9n1S0UcKmVTzLfFWO9aa38Tzb1CG1vjHUhTEi4VurH9H3UcE=,iv:k1lckal5zGmzdh4s/dVIoOuROX+Amx3S5KRYdftfVms=,tag:+yQfYphAgZr7+YJIi3Q5Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
