apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-secret
    annotations:
        replicator.v1.mittwald.de/replicate-to: database, default, storage
stringData:
    access-token: ENC[AES256_GCM,data:GxRRUB3BE3uKNTeK4NcLc82cLFKPNICHIhBZnNxO5gnreXrDNLaTlIYyUMUQXABzYOYtXnB5BJESWNj01LtecJRmfqNJdKTVk1IblBfQLykzMyGsf0FnbraBQyFqoQ==,iv:2b+lSUd3EgM/w/FpwXid7eNaGRIpUHzMmJO2U2+ESik=,tag:qJEXIpDJIugmlhemJ4VLMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmFwNjJrNExSTk9rR1RM
            UjhWZ1p0eTRsWVh2RjcwOWFuQUZDN0dTTzJrCmtvYSt5RXp4dTR0T0JpaFV6RHlr
            cnBSZE44bEVHWjU3WCtNbGtKNWEyVzQKLS0tIHhCdXFES3ZPYzNVbFQyWldSRC9q
            SnZVRVBDeWFlcGtOei9hS0dqdWFIdFEKFVdJnp/x6635lkyDwLU7yuYfVMwkwitu
            H6LPNYa9/fOyFESh5QnGCmIQ62R5ncGlio1rMMpCsy7xlXsk6JaALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T18:24:57Z"
    mac: ENC[AES256_GCM,data:xVPTZiJifIUeF3VWPTHytFQGXOJNDf+0u5SBI6fKrwOFhWm8LZ5ZsxQdh3ZDw9R3ggbM0momxjiqsyqzEviBRf9GVgEb69EXQrIx8QBTcrYTkHhGM3MSp99Em/aheY5UOJzhmEmJ90USN6BPjosPnjozxFGT2u3+jiq7CpG8elQ=,iv:RkEY0AAj9R/UbftRxa8M5ZiZAf6yCsGTXjl/kAg1MVY=,tag:HrG4A9nwLvVOx45NUC+VxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
