apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-secret
    annotations:
        replicator.v1.mittwald.de/replicate-to: default
stringData:
    access-token: ENC[AES256_GCM,data:GxRRUB3BE3uKNTeK4NcLc82cLFKPNICHIhBZnNxO5gnreXrDNLaTlIYyUMUQXABzYOYtXnB5BJESWNj01LtecJRmfqNJdKTVk1IblBfQLykzMyGsf0FnbraBQyFqoQ==,iv:2b+lSUd3EgM/w/FpwXid7eNaGRIpUHzMmJO2U2+ESik=,tag:qJEXIpDJIugmlhemJ4VLMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tn5txs6m4kdq4cfk9t7k5mcr58svuf0uwlrrmsxc9aslj4x9y4skkzs74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmFwNjJrNExSTk9rR1RM
            UjhWZ1p0eTRsWVh2RjcwOWFuQUZDN0dTTzJrCmtvYSt5RXp4dTR0T0JpaFV6RHlr
            cnBSZE44bEVHWjU3WCtNbGtKNWEyVzQKLS0tIHhCdXFES3ZPYzNVbFQyWldSRC9q
            SnZVRVBDeWFlcGtOei9hS0dqdWFIdFEKFVdJnp/x6635lkyDwLU7yuYfVMwkwitu
            H6LPNYa9/fOyFESh5QnGCmIQ62R5ncGlio1rMMpCsy7xlXsk6JaALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T21:54:26Z"
    mac: ENC[AES256_GCM,data:TSE2nyaPW0rEB58pxwDlJAeCrAXOaNkxQNuNt9YKGXAJ/zx8ai09gCpY8vVO46vwtGJrCD1QphDe6ukzxIqYwwsyEh4cjL3c9dS0VhVSF/q1ub4K1AHy72pROx/LZRBuxangHxD/HywbZxqXmpvt7n3D9uid4GvkrGS9mddrM/w=,iv:fxzvgG8WKLRII64me4juOZhY5yU3thkughpQkiesjp4=,tag:DhWf6S91Hv01ySUPlkXoAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
